language: python
python:
  - "3.6"
services:
  - mysql
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
script:
  - pipenv run coverage run --source='.' manage.py test --noinput
  - pipenv run coverage report
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - mysql -e 'create database littleleviathan;'
  - pipenv run python manage.py migrate
  - npm install
  - npm build
notifications:
  email: false
