language: python
dist: precise
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pipenv run coverage run --source='.' manage.py test --noinput && coverage report
before_install:
  - rvm install 2.0.0
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - gem install sass
  - mysql -e 'create database littleleviathan;'
  - pipenv run python manage.py migrate
  - npm install
  - sass assets/css/site.scss assets/css/site.css
  - pipenv run python manage.py collectstatic --noinput --ignore *.sass
