language: python
python:
  - "3.6"
services:
  - mysql
script:
  - pipenv run coverage run --source='.' manage.py test --noinput && coverage report
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - mysql -e 'create database littleleviathan;'
  - pipenv run python manage.py migrate
  - npm ci
  - npm build
notifications:
  email: false
