language: python
cache: pip
python:
  - "3.4"
  - "3.5"
script:
  - python manage.py test --noinput
before_install:
  - rvm install 2.0.0
install:
  - pip install -r dev-requirements.txt
before_script:
  - gem install sass
  - mysql -e 'create database littleleviathan;'
  - python manage.py migrate
  - npm install
  - sass assets/css/site.sass assets/css/site.css
  - python manage.py collectstatic --noinput --ignore *.sass
